#!/usr/bin/env bash
# Télécharge les images du site CZE France en local (à lancer dans le dossier site-internet)
set -e
echo "Téléchargement des images..."
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-stockage-vhu.jpg" "https://cze-france.fr/wp-content/uploads/2023/01/CANTILEVER-4.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-simple.png" "https://cze-france.fr/wp-content/uploads/2023/07/6.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-double.png" "https://cze-france.fr/wp-content/uploads/2023/07/7.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-flyer.png" "https://cze-france.fr/wp-content/uploads/2023/07/FLYER-CZE-1.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-dimensions.png" "https://cze-france.fr/wp-content/uploads/2023/07/pub-Cantilever-2.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-vhu-1.png" "https://cze-france.fr/wp-content/uploads/2023/07/4-1.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cantilever-vhu-2.png" "https://cze-france.fr/wp-content/uploads/2023/07/5-1.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/potence-yydgg.jpg" "https://cze-france.fr/wp-content/uploads/2023/07/potence.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/cisaille-s211.jpg" "https://cze-france.fr/wp-content/uploads/2023/06/1-2006121F25V43.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/separateur-de-cuivre.png" "https://cze-france.fr/wp-content/uploads/2023/10/Separateur-de-cuivre-CZE-FRANCE.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/separateur-de-cuivre-1.png" "https://cze-france.fr/wp-content/uploads/2023/10/Separateur-de-cuivre-1.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/separateur-de-cuivre-3.png" "https://cze-france.fr/wp-content/uploads/2023/10/Separateur-de-cuivre-3.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/separateur-de-cuivre-4.png" "https://cze-france.fr/wp-content/uploads/2023/10/Separateur-de-cuivre-4.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/products/separateur-de-cuivre-5.png" "https://cze-france.fr/wp-content/uploads/2023/10/Separateur-de-cuivre-5.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/allo-casse-auto.png" "https://cze-france.fr/wp-content/uploads/2023/05/ALLO-CASSE-AUTO.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/mazard-pieces-auto.png" "https://cze-france.fr/wp-content/uploads/2023/05/mazard-pieces-auto.png"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/lga.jpg" "https://cze-france.fr/wp-content/uploads/2023/05/LGA-e1685110496351.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/rm-auto.jpg" "https://cze-france.fr/wp-content/uploads/2023/05/RM-AUTO.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/ad2r.jpg" "https://cze-france.fr/wp-content/uploads/2023/05/AD-scaled.jpg"
curl -fL --create-dirs -e "https://cze-france.fr/" -o "assets/img/clients/allo-depannage.jpg" "https://cze-france.fr/wp-content/uploads/2023/05/allo-depannage.jpg"
curl -fL --create-dirs -e "https://czn-machinery.com/" -o "assets/img/products/czn-mini-pelle.webp" "https://czn-machinery.com/images/logos/sonca-mini-pelle-sjw-25-hero.webp"
curl -fL --create-dirs -e "https://czn-machinery.com/" -o "assets/img/products/czn-mini-pelle-og.jpg" "https://czn-machinery.com/images/czn-mini-pelle-og.jpg"
echo "✅ Terminé. Toutes les images sont dans assets/img/."
